update .net for check-format

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,28 +16,28 @@ jobs:
 
   # Note that vcpkg dependencies takes the majority of the build time.
   # We cache them using GitHub Actions cache, making the scripts below a bit more complex.
-  # check-format:
-  #   if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
-  #   name: Check format
-  #   runs-on: ubuntu-22.04
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
-  #     - name: Setup .NET SDK v6.0.x
-  #       uses: actions/setup-dotnet@v3
-  #       with:
-  #         dotnet-version: 6.0.x
-  #     - name: Code formating check
-  #       run: |
-  #         dotnet tool restore
-  #         dotnet jb cleanupcode "csharp" "csharp.test" "csharp.benchmark" --profile="Built-in: Reformat Code" --settings="ParquetSharp.DotSettings" --verbosity=WARN
+  check-format:
+    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
+    name: Check format
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Setup .NET SDK v7.0.x
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: 7.0.x
+      - name: Code formating check
+        run: |
+          dotnet tool restore
+          dotnet jb cleanupcode "csharp" "csharp.test" "csharp.benchmark" --profile="Built-in: Reformat Code" --settings="ParquetSharp.DotSettings" --verbosity=WARN
 
-  #         files=($(git diff --name-only))
-  #         if [ ${#files[@]} -gt 0 ]
-  #         then
-  #           for file in $files; do echo "::error file=$file::Code format check failed"; done
-  #           exit 1
-  #         fi
+          files=($(git diff --name-only))
+          if [ ${#files[@]} -gt 0 ]
+          then
+            for file in $files; do echo "::error file=$file::Code format check failed"; done
+            exit 1
+          fi
 
   # Build everything on all platorms (thus testing the developer workflow).
   # Upload the native shared libraries as artifacts.
