test public-release process

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -276,57 +276,56 @@ jobs:
       run: docker run --rm --platform linux/arm64/v8 -v $PWD:$PWD -w $PWD mcr.microsoft.com/dotnet/sdk:6.0 dotnet test csharp.test --configuration=Release --framework ${{ matrix.dotnet }}
 
   # Virtual job that can be configured as a required check before a PR can be merged.
-  # TODO: re-enable and test this
-  # all-required-checks-done:
-  #   name: All required checks done
-  #   needs:
-  #     - check-format
-  #     - test-nuget
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - run: echo "All required checks done"
+  all-required-checks-done:
+    name: All required checks done
+    needs:
+      - check-format
+      - test-nuget
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "All required checks done"
 
   # Create a GitHub release and publish the NuGet packages to nuget.org when a tag is pushed.
-  # TODO: re-enable and test this
-  # publish-release:
-  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && !github.event.repository.fork
-  #   name: Publish release
-  #   runs-on: ubuntu-latest
-  #   needs: all-required-checks-done
-  #   steps:
-  #   - name: Checkout
-  #     uses: actions/checkout@v3
-  #   - name: Check version
-  #     id: check-version
-  #     shell: pwsh
-  #     run: |
-  #       $version = (Select-Xml -Path ./csharp/ParquetSharp.csproj -XPath '/Project/PropertyGroup/Version/text()').node.Value
-  #       $tag = "${{ github.ref }}".SubString(10)
-  #       if (-not ($tag -eq $version)) {
-  #         echo "::error ::There is a mismatch between the project version ($version) and the tag ($tag)"
-  #         exit 1
-  #       }
-  #       echo "version=$version" >> $env:GITHUB_OUTPUT
-  #   - name: Download NuGet artifact
-  #     uses: actions/download-artifact@v3
-  #     with:
-  #       name: nuget-package
-  #       path: nuget
-  #   - name: Setup .NET SDK v6.0.x
-  #     uses: actions/setup-dotnet@v3
-  #     with:
-  #       dotnet-version: 6.0.x
-  #   # if version contains "-" treat it as pre-release
-  #   # example: 1.0.0-beta1
-  #   - name: Create release
-  #     uses: softprops/action-gh-release@v1
-  #     with:
-  #       name: ParquetSharp ${{ steps.check-version.outputs.version }}
-  #       draft: true
-  #       prerelease: ${{ contains(steps.check-version.outputs.version, '-') }}
-  #       files: |
-  #         nuget/ParquetSharp.${{ steps.check-version.outputs.version }}.nupkg
-  #     env:
-  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #   - name: Publish to NuGet
-  #     run: dotnet nuget push nuget/ParquetSharp.${{ steps.check-version.outputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+  publish-release:
+    # FIXME: commented out for test purpose
+    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && !github.event.repository.fork
+    name: Publish release
+    runs-on: ubuntu-latest
+    needs: all-required-checks-done
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: Check version
+      id: check-version
+      shell: pwsh
+      run: |
+        $version = (Select-Xml -Path ./csharp/ParquetSharp.csproj -XPath '/Project/PropertyGroup/Version/text()').node.Value
+        $tag = "${{ github.ref }}".SubString(10)
+        if (-not ($tag -eq $version)) {
+          echo "::error ::There is a mismatch between the project version ($version) and the tag ($tag)"
+          exit 1
+        }
+        echo "version=$version" >> $env:GITHUB_OUTPUT
+    - name: Download NuGet artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: nuget-package
+        path: nuget
+    - name: Setup .NET SDK v7.0.x
+      uses: actions/setup-dotnet@v3
+      with:
+        dotnet-version: 7.0.x
+    # if version contains "-" treat it as pre-release
+    # example: 1.0.0-beta1
+    - name: Create release
+      uses: softprops/action-gh-release@v1
+      with:
+        name: ParquetSharp ${{ steps.check-version.outputs.version }}
+        draft: true
+        prerelease: ${{ contains(steps.check-version.outputs.version, '-') }}
+        files: |
+          nuget/ParquetSharp.${{ steps.check-version.outputs.version }}.nupkg
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Publish to NuGet
+      run: dotnet nuget push nuget/ParquetSharp.${{ steps.check-version.outputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
